"""LADDER-style difficulty ladder for ARC (Simonds & Yoneda 2025: recursively generate simpler variants of a problem,
verify them, learn on them, and at test time learn on variants of the test problem itself).

Adaptation to ARC, where the only verified data are the demonstration pairs of each task:
  * Variant generator: from a demo pair (in, out) build SIMPLER pairs of the same task -
      - 'subset': keep a fraction f of the objects, erase the others from the input and the output cells around them;
      - 'crop'  : a window of fraction f of the grid whose border cuts no object.
    Applying it with f = 0.7, 0.5, 0.3 gives the ladder levels 1, 2, 3 (level 0 = the original demo).
  * Verification: variants are derived from VERIFIED outputs; a variant is kept only if it is still a change-carrying
    pair and every colour transition it shows (in-colour -> out-colour) already occurs in the original pair
    (rejects variants that would teach a rule the task does not have). Only same-shape tasks get variants.
  * Difficulty-driven schedule: per (task, level) the model's own exact-match rate is tracked (EMA); sampling weight is
    highest at the FRONTIER (success ~ 0.5), low for solved or hopeless levels, so training climbs the ladder per task.
  * TTRL stage: the same schedule restricted to the evaluation tasks' demos (test-time learning, no test labels).
Differences from the paper: supervised cross-entropy instead of GRPO, and the 'easier variants' are generated by rules
instead of by the model.
"""
from __future__ import annotations

import math

import numpy as np
import torch

from arcgen.core import find_objects

LEVELS = (0.7, 0.5, 0.3)


def _transitions(a, b):
    m = a != b
    return {(int(x), int(y)) for x, y in zip(a[m], b[m])}


def _dilate(m):
    out = m.copy()
    for dy in (-1, 0, 1):
        for dx in (-1, 0, 1):
            s = np.zeros_like(m)
            h, w = m.shape
            s[max(0, dy):h + min(0, dy), max(0, dx):w + min(0, dx)] = m[max(0, -dy):h - max(0, dy), max(0, -dx):w - max(0, dx)]
            out |= s
    return out


def _valid(vin, vout, orig_in, orig_out):
    if vin.size == 0 or vin.shape != vout.shape or min(vin.shape) < 2:
        return False
    had_change = (orig_in != orig_out).any()
    if had_change and not (vin != vout).any():
        return False                                    # the rule would not be visible any more
    return _transitions(vin, vout) <= _transitions(orig_in, orig_out)


def subset_variant(inp, out, f, rng):
    objs = find_objects(inp, "m8")
    if len(objs) < 2:
        return None
    keep_n = max(1, int(round(f * len(objs))))
    keep = set(rng.choice(len(objs), keep_n, replace=False).tolist())
    erase = np.zeros(inp.shape, bool); kept = np.zeros(inp.shape, bool)
    for i, o in enumerate(objs):
        (kept if i in keep else erase)[o.rows, o.cols] = True
    vin = np.where(erase, 0, inp)
    region = _dilate(erase) & ~kept
    vout = np.where(region, 0, out)
    return (vin, vout) if _valid(vin, vout, inp, out) else None


def crop_variant(inp, out, f, rng, tries=24):
    H, W = inp.shape
    h, w = max(3, math.ceil(f * H)), max(3, math.ceil(f * W))
    if h >= H and w >= W:
        return None
    union = (inp != 0) | (out != 0)
    comp = find_objects(np.where(union, 1, 0), "m8")
    for _ in range(tries):
        y, x = int(rng.integers(0, H - h + 1)), int(rng.integers(0, W - w + 1))
        ok = True
        for o in comp:
            inside = (o.rows >= y) & (o.rows < y + h) & (o.cols >= x) & (o.cols < x + w)
            if inside.any() and not inside.all():
                ok = False
                break
        if ok:
            vin, vout = inp[y:y + h, x:x + w], out[y:y + h, x:x + w]
            if _valid(vin, vout, inp, out):
                return vin.copy(), vout.copy()
    return None


def make_variants(inp, out, rng, levels=LEVELS, per_level=2):
    """-> list of (level, vin, vout); level 1..len(levels) (1 = slightly simpler)."""
    if inp.shape != out.shape:
        return []
    res, seen = [], set()
    for lv, f in enumerate(levels, 1):
        for kind in (subset_variant, crop_variant):
            for _ in range(per_level):
                v = kind(inp, out, f, rng)
                if v is None:
                    continue
                key = (v[0].shape, v[0].tobytes(), v[1].tobytes())
                if key not in seen:
                    seen.add(key)
                    res.append((lv, *v))
    return res


def build_ladder(tasks, seed=0, levels=LEVELS, per_level=2):
    """Attach ``task['variants'][level] = [(vin, vout), ...]`` to every task (in place)."""
    rng = np.random.default_rng(seed)
    for t in tasks:
        t["variants"] = {}
        for inp, out in t["demos"]:
            for lv, vin, vout in make_variants(inp, out, rng, levels, per_level):
                t["variants"].setdefault(lv, []).append((vin, vout))
    return tasks


class LadderState:
    """Shared (across DataLoader workers) per-(task, level) success EMA and the sampling weights derived from it."""

    def __init__(self, n_tasks, n_levels, base0=0.5):
        self.n_levels, self.base0 = n_levels, base0
        self.ema = torch.full((n_tasks, n_levels + 1), 0.5).share_memory_()
        self.w = torch.ones(n_tasks, n_levels + 1).share_memory_()

    def update(self, task, level, success, alpha=0.3):
        self.ema[task, level] = (1 - alpha) * self.ema[task, level] + alpha * float(success)
        self.refresh(task)

    def refresh(self, task):
        s = self.ema[task]
        frontier = 0.05 + 4.0 * s * (1 - s)               # peaks at s = 0.5: not solved yet, not hopeless
        frontier[0] = self.base0 + 0.5 * frontier[0]       # the original demos always keep a floor of attention
        self.w[task] = frontier

    def level_probs(self, task, available):
        w = self.w[task][list(available)].numpy().astype(float)
        return w / w.sum()


@torch.no_grad()
def probe(model, tasks, state, rng, device="cpu", n=48):
    """Measure the model's own exact-match on random (task, level) variants and update the ladder state."""
    from .data import make_sample, collate
    model.eval()
    picks = []
    for _ in range(n):
        ti = int(rng.integers(len(tasks)))
        t = tasks[ti]
        levels = [0] + [l for l in t.get("variants", {}) if t["variants"][l]]
        lv = int(rng.choice(levels))
        pool = t["demos"] if lv == 0 else t["variants"][lv]
        inp, out = pool[int(rng.integers(len(pool)))]
        if max(inp.shape) <= model.G and max(out.shape) <= model.G:
            picks.append((ti, lv, inp, out))
    if not picks:
        return 0.0
    items = [make_sample(i, o, ti, model.G, model.K, rng, A=model.A, a=0) for ti, lv, i, o in picks]
    b = {k: v.to(device) for k, v in collate(items).items()}
    pred = model(b, return_all=False).argmax(-1).view(len(picks), model.G, model.G)
    hit = (pred == b["target"]).all((1, 2)).cpu().numpy()
    for (ti, lv, _, _), h in zip(picks, hit):
        state.update(ti, lv, h)
    return float(hit.mean())
